name: Next.js Application Tests

on:
  push:
    branches: [ main, develop ]
    paths:
      - 'app/**'
      - 'package.json'
      - 'next.config.js'
      - 'tailwind.config.ts'
  pull_request:
    branches: [ main ]

jobs:
  nextjs-tests:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
    
    - name: Cache dependencies
      uses: actions/cache@v4
      with:
        path: |
          ~/.npm
          node_modules
          .next/cache
        key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-node-
    
    - name: Install dependencies
      run: npm ci
    
    - name: TypeScript type checking
      run: npx tsc --noEmit
    
    - name: ESLint check
      run: npm run lint
    
    - name: Check for unused dependencies
      run: |
        npx depcheck --json > depcheck-report.json || echo "Dependency check completed"
    
    - name: Test build process
      run: npm run build
    
    - name: Test production build
      run: |
        # Test that the production build works
        npm run build
        npm start &
        SERVER_PID=$!
        sleep 10
        
        # Test basic page load
        if curl -f http://localhost:3000 > /dev/null 2>&1; then
          echo "✓ Homepage loads successfully"
        else
          echo "✗ Homepage failed to load"
          exit 1
        fi
        
        # Test API routes
        if curl -f http://localhost:3000/api/mapbox-token > /dev/null 2>&1; then
          echo "✓ Mapbox token API accessible"
        else
          echo "✗ Mapbox token API failed"
        fi
        
        kill $SERVER_PID || true
    
    - name: Check bundle size
      run: |
        # Check if bundle size is reasonable
        npm run build
        if [ -d ".next" ]; then
          echo "✓ Next.js build completed successfully"
          du -sh .next/
        else
          echo "✗ Next.js build failed"
          exit 1
        fi
    
    - name: Test environment variables
      env:
        NEXT_PUBLIC_MAPBOX_TOKEN: test_token
        SUPABASE_URL: https://test.supabase.co
        SUPABASE_ANON_KEY: test_key
      run: |
        # Test that environment variables are properly handled
        npm run build
        echo "✓ Environment variables handled correctly"
    
    - name: Check for accessibility issues
      run: |
        # Basic accessibility checks
        if grep -r "alt=" app/ --include="*.tsx" --include="*.jsx"; then
          echo "✓ Alt attributes found in images"
        else
          echo "⚠ No alt attributes found in images"
        fi
        
        if grep -r "aria-label" app/ --include="*.tsx" --include="*.jsx"; then
          echo "✓ ARIA labels found"
        else
          echo "⚠ No ARIA labels found"
        fi
    
    - name: Check for performance issues
      run: |
        # Check for common performance issues
        if grep -r "useEffect.*\[\]" app/ --include="*.tsx" --include="*.jsx"; then
          echo "⚠ useEffect with empty dependency array found"
        else
          echo "✓ No useEffect with empty dependencies"
        fi
        
        if grep -r "console.log" app/ --include="*.tsx" --include="*.jsx" --exclude="*.test.*" --exclude="*.spec.*"; then
          echo "⚠ console.log statements found in production code"
        else
          echo "✓ No console.log statements in production code"
        fi
    
    - name: Upload test reports
      uses: actions/upload-artifact@v4
      with:
        name: nextjs-test-reports
        path: |
          depcheck-report.json
        retention-days: 7 