name: Vercel Preview/Production Deployment (Official CLI)

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
  VERCEL_ORG_ID:    ${{ secrets.VERCEL_ORG_ID }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: Production
    steps:
      - uses: actions/checkout@v4
      - name: Install Vercel CLI
        run: npm i -g vercel@latest
      - name: Set Vercel Environment
        id: vercel-env
        run: |
          if [[ "${GITHUB_REF}" == "refs/heads/main" ]]; then
            echo "env=production" >> $GITHUB_OUTPUT
          else
            echo "env=preview" >> $GITHUB_OUTPUT
          fi
      - name: Pull Vercel Environment Info
        run: vercel pull --yes --environment=${{ steps.vercel-env.outputs.env }} --token ${{ secrets.VERCEL_TOKEN }}
      - name: Build Project Artifacts
        run: |
          if [ "${{ github.ref }}" = "refs/heads/main" ]; then
            vercel build --prod --token ${{ secrets.VERCEL_TOKEN }}
          else
            vercel build --token ${{ secrets.VERCEL_TOKEN }}
          fi
      - name: Deploy to Vercel
        run: |
          if [ "${{ github.ref }}" = "refs/heads/main" ]; then
            vercel deploy --prebuilt --prod --token ${{ secrets.VERCEL_TOKEN }}
          else
            vercel deploy --prebuilt --token ${{ secrets.VERCEL_TOKEN }}
          fi 