name: Vercel Preview/Production Deployment (Official CLI)

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
  VERCEL_ORG_ID:    ${{ secrets.VERCEL_ORG_ID }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Vercel CLI
        run: npm i -g vercel@latest
      - name: Pull Vercel Environment Info
        run: vercel pull --yes --environment=${{ github.ref == 'refs/heads/main' && 'production' || 'preview' }} --token ${{ secrets.VERCEL_TOKEN }}
      - name: Build Project Artifacts
        run: vercel build --token ${{ secrets.VERCEL_TOKEN }}
      - name: Deploy to Vercel
        run: |
          if [ "${{ github.ref }}" = "refs/heads/main" ]; then
            vercel deploy --prebuilt --prod --token ${{ secrets.VERCEL_TOKEN }}
          else
            vercel deploy --prebuilt --token ${{ secrets.VERCEL_TOKEN }}
          fi 