name: Deploy to Vercel (Preview & Prod)

on:
  push:
    branches: [main]          # → production
  pull_request:               # → preview
    branches: ["*"]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      # reuse the same lockfile tooling as the quality job
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
      
      - name: Install dependencies
        run: npm ci
      
      - name: Build application
        run: npm run build          # creates the .next artefact

      - name: Install Vercel CLI
        run: npm i -g vercel@latest

      - name: Deploy via Vercel CLI
        env:
          VERCEL_TOKEN:       ${{ secrets.VERCEL_TOKEN }}
          VERCEL_ORG_ID:      ${{ secrets.VERCEL_ORG_ID }}
          VERCEL_PROJECT_ID:  ${{ secrets.VERCEL_PROJECT_ID }}
        run: |
          # use the already-built artefact to avoid a double build
          if [[ "$GITHUB_EVENT_NAME" == "push" ]]; then
            echo "🚀 Deploying to production..."
            vercel deploy --prod --prebuilt --confirm \
              --token $VERCEL_TOKEN --scope $VERCEL_ORG_ID
          else
            echo "🔍 Creating preview deployment..."
            vercel deploy --prebuilt --token $VERCEL_TOKEN \
              --scope $VERCEL_ORG_ID
          fi 