name: Frontend Quality Check

on:
  push:
    branches: [ main, develop ]
    paths:
      - 'app/**'
      - 'package.json'
      - 'next.config.js'
      - 'tailwind.config.ts'
  pull_request:
    branches: [ main ]
    paths:
      - 'app/**'
      - 'package.json'

jobs:
  frontend-quality:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci
    
    - name: TypeScript type checking
      run: npx tsc --noEmit
    
    - name: ESLint check
      run: npm run lint
    
    - name: Check for console errors
      run: |
        # Check for console.log statements in production code
        if grep -r "console.log" app/ --exclude="*.test.*" --exclude="*.spec.*"; then
          echo "Warning: console.log statements found in app files"
        else
          echo "✓ No console.log statements found in app files"
        fi
    
    - name: Validate Next.js configuration
      run: |
        # Check if next.config.js exists and is valid
        if [ -f "next.config.js" ]; then
          node -c next.config.js && echo "✓ next.config.js is valid"
        else
          echo "✗ next.config.js not found"
          exit 1
        fi
    
    - name: Check for Mapbox token usage
      run: |
        # Ensure Mapbox token is being used from environment
        if grep -r "process.env.NEXT_PUBLIC_MAPBOX_TOKEN" app/; then
          echo "✓ Mapbox token is being used from environment"
        else
          echo "Warning: Mapbox token usage not found in app files"
        fi
    
    - name: Check for Supabase integration
      run: |
        # Ensure Supabase is properly integrated
        if grep -r "@supabase/supabase-js" app/; then
          echo "✓ Supabase integration found"
        else
          echo "Warning: Supabase integration not found"
        fi
    
    - name: Build test
      run: npm run build 