name: Frontend Quality Check

on:
  push:
    branches: [ main, develop ]
    paths:
      - 'static/**'
      - 'templates/**'
      - 'package.json'
      - 'vercel.json'
  pull_request:
    branches: [ main ]
    paths:
      - 'static/**'
      - 'templates/**'

jobs:
  frontend-quality:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
    
    - name: Install dependencies
      run: |
        if [ -f "package.json" ]; then
          npm ci
        else
          echo "No package.json found, skipping npm install"
        fi
    
    - name: Check for console errors
      run: |
        # Check for console.log statements in production code
        if grep -r "console.log" static/; then
          echo "Warning: console.log statements found in static files"
        else
          echo "✓ No console.log statements found in static files"
        fi
    
    - name: Validate HTML templates
      run: |
        # Basic HTML validation
        python -c "
        import os
        try:
            from bs4 import BeautifulSoup
            for file in os.listdir('templates'):
                if file.endswith('.html'):
                    with open(f'templates/{file}', 'r') as f:
                        soup = BeautifulSoup(f.read(), 'html.parser')
                        print(f'✓ {file} is valid HTML')
        except ImportError:
            print('BeautifulSoup not available, skipping HTML validation')
        "
    
    - name: Check JavaScript syntax
      run: |
        # Basic JavaScript syntax check
        for file in static/*.js; do
          if [ -f "$file" ]; then
            node -c "$file" && echo "✓ $file syntax is valid"
          fi
        done
    
    - name: Check for Mapbox token usage
      run: |
        # Ensure Mapbox token is being fetched from API
        if grep -r "mapboxgl.accessToken" static/; then
          echo "✓ Mapbox token is being set from API"
        else
          echo "Warning: Mapbox token not found in static files"
        fi 